name: Swift

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        pod install --repo-update --clean-install
        xcodebuild test -workspace GithubActionTest.xcworkspace -scheme GithubActionTest -destination 'platform=iOS Simulator,name=iPhone 12 Pro'
