name: Swift

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app
#     - name: Make project
#       run: make project
    - name: Run tests
      run: |
        pod install --repo-update --clean-install
        xcodebuild test -workspace GithubActionTest.xcworkspace -scheme GithubActionTest -destination 'platform=iOS Simulator,name=iPhone 12 Pro'
        
        
#         strategy:

#       matrix:

#         platform: [iOS]

#         include:

#           - platform: iOS

#             sdk: iphonesimulator

#             destination: "name=iPhone 11"

#     steps:

#       - uses: actions/checkout@v2

#       - name: Select Xcode 12

#         run: sudo xcode-select -s /Applications/Xcode_12.app

#       - name: Make project

#         run: make project

# #       - name: Install Pods

# #         run: pod install --project-directory=./

#       - name: Run tests

#         run: set -o pipefail && xcodebuild -workspace GithubActionTest.xcworkspace -scheme GithubActionTest -enableCodeCoverage YES -sdk ${{ matrix.sdk }} -destination "${{ matrix.destination }}" test | xcpretty -c -r html --output logs/${{ matrix.platform }}.html

#       - uses: codecov/codecov-action@v1.0.13

#         with:

#           token: 4842bea2-22dc-479b-b0a4-ff0b22aa9818

#           name: CombineCocoa

#       - uses: actions/upload-artifact@v1

#         with:

#           name: build-logs-${{ github.run_id }}

#           path: logs
