name: Swift

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.app
#     - name: Make project
#       run: make project
    - name: Run tests
      run: |
        pod install --repo-update --clean-install
        set -o pipefail && xcodebuild test -workspace GithubActionTest.xcworkspace -scheme GithubActionTest -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.5'
        
